version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pascwarts-db
    environment:
      POSTGRES_DB: pascwarts
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pascwarts-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pascwarts-backend
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: pascwarts
      DATABASE_USER: postgres
      DATABASE_PASSWORD: password123
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pascwarts-network
    command: npm run start:dev

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: pascwarts-frontend
  #   environment:
  #     REACT_APP_API_URL: http://localhost:3001
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   networks:
  #     - pascwarts-network
  #   command: npm start

volumes:
  postgres_data:

networks:
  pascwarts-network:
    driver: bridge